table dim_sector
	lineageTag: 5046a8a8-c8aa-43e1-965a-fdce8dca5e44

	column sector_code
		dataType: string
		lineageTag: 198d74f6-9b98-4eb3-83ec-cd9856f150b0
		summarizeBy: none
		sourceColumn: sector_code

		annotation SummarizationSetBy = Automatic

	column sector_name
		dataType: string
		lineageTag: f6e4ca45-fb61-4ab5-abe3-34d4f57c057f
		summarizeBy: none
		sourceColumn: sector_name

		annotation SummarizationSetBy = Automatic

	partition dim_sector = m
		mode: import
		source =
				let
				     Source = Csv.Document(File.Contents(DataFolder & "\MB_dim_sector.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sector_code", type text}, {"sector_name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

