table dim_district
	lineageTag: 4debedb3-5434-4901-8150-f4e49a5f30a0

	column district_code
		dataType: string
		lineageTag: 38239ffe-561e-4955-8881-943b04489fa6
		summarizeBy: none
		sourceColumn: district_code

		annotation SummarizationSetBy = Automatic

	column district_name
		dataType: string
		lineageTag: 1cdb7bfe-7e9e-4ae8-9a43-749024b7bee2
		summarizeBy: none
		sourceColumn: district_name

		annotation SummarizationSetBy = Automatic

	column state_code
		dataType: string
		lineageTag: 0185ee89-034d-420d-9fd8-b3ffbbdc5667
		summarizeBy: none
		sourceColumn: state_code

		annotation SummarizationSetBy = Automatic

	column state_name
		dataType: string
		lineageTag: bc2c4519-5838-44a2-a52a-c6faf1636c47
		summarizeBy: none
		sourceColumn: state_name

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 1eafc530-bd9c-41df-9d64-a4c4729a0303
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 50a12887-44ef-4dcb-8b8e-3ba5fd49ebd1
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_pilot
		dataType: int64
		formatString: 0
		lineageTag: bca1829c-da54-4148-b4e2-4870d5db2d9b
		summarizeBy: sum
		sourceColumn: is_pilot

		annotation SummarizationSetBy = Automatic

	column destination_cluster
		dataType: string
		lineageTag: 72ba3b27-3cb6-4d89-a4b6-bac836f75e6e
		summarizeBy: none
		sourceColumn: destination_cluster

		annotation SummarizationSetBy = Automatic

	partition dim_district = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\MB_dim_district.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"district_code", type text}, {"district_name", type text}, {"state_code", type text}, {"state_name", type text}, {"latitude", type number}, {"longitude", type number}, {"is_pilot", Int64.Type}, {"destination_cluster", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

