table dim_evidence_level
	lineageTag: 9799d483-c15e-4324-a56c-b11bb9747ab5

	column level_code
		dataType: string
		lineageTag: 6ca66a3c-c220-4480-a0ab-e340f05e2208
		summarizeBy: none
		sourceColumn: level_code

		annotation SummarizationSetBy = Automatic

	column level_name_en
		dataType: string
		lineageTag: e9605a9e-41a3-4f9a-bab5-c6512ac7f80a
		summarizeBy: none
		sourceColumn: level_name_en
		sortByColumn: sort_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column level_name_zh
		dataType: string
		lineageTag: fc073375-0dad-4d49-99b1-1142ff2ebd4f
		summarizeBy: none
		sourceColumn: level_name_zh

		annotation SummarizationSetBy = Automatic

	column hex_color
		dataType: string
		lineageTag: f7825df0-83b3-4cb5-9b11-795258f33a04
		summarizeBy: none
		sourceColumn: hex_color

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: dba03374-6f27-4961-9f2b-cac5e155383e
		summarizeBy: none
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	partition dim_evidence_level = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\MB_dim_evidence_level.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"level_code", type text}, {"level_name_en", type text}, {"level_name_zh", type text}, {"hex_color", type text}, {"sort_order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

