table fct_workforce_exposure
	lineageTag: 9affc350-28c9-4d94-963b-4da5045605a9

	column district_code
		dataType: string
		lineageTag: f44863e9-44c8-49a6-b79b-9edc92e4f83f
		summarizeBy: none
		sourceColumn: district_code

		annotation SummarizationSetBy = Automatic

	column occupation_code
		dataType: string
		lineageTag: c39e3b91-1e97-402c-ba01-089a06ee3f88
		summarizeBy: none
		sourceColumn: occupation_code

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 03c88ddd-8d6e-4ac2-af99-8e8e07bbaee2
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column tourism_linked_workers
		dataType: int64
		formatString: 0
		lineageTag: 1c8255ad-ead1-4f57-90f2-050181e558bc
		summarizeBy: sum
		sourceColumn: tourism_linked_workers

		annotation SummarizationSetBy = Automatic

	column tourism_dependency
		dataType: double
		lineageTag: 3e4f32d2-1a3e-451c-aed0-af42623b9ce2
		summarizeBy: sum
		sourceColumn: tourism_dependency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column exposure_months
		dataType: double
		lineageTag: 96a18758-d172-4c36-af1b-49e8b11e28cc
		summarizeBy: sum
		sourceColumn: exposure_months

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column wme
		dataType: double
		lineageTag: 767b97c6-5065-4b13-977b-a53a5d083573
		summarizeBy: sum
		sourceColumn: wme

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column priority_band
		dataType: string
		lineageTag: de00635d-e576-4aab-be36-e3f722644a9b
		summarizeBy: none
		sourceColumn: priority_band

		annotation SummarizationSetBy = Automatic

	column evidence_level
		dataType: string
		lineageTag: 0848f9e9-e0af-41ab-a5cd-b5b4ef7475f1
		summarizeBy: none
		sourceColumn: evidence_level

		annotation SummarizationSetBy = Automatic

	partition fct_workforce_exposure = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\MB_fct_workforce_exposure.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"district_code", type text}, {"occupation_code", type text}, {"year", Int64.Type}, {"tourism_linked_workers", Int64.Type}, {"tourism_dependency", type number}, {"exposure_months", type number}, {"wme", type number}, {"priority_band", type text}, {"evidence_level", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

