table fct_skill_evidence
	lineageTag: ec27a748-cfa3-4140-9bb5-6f448b9d27bf

	column occupation_code
		dataType: string
		lineageTag: 991ba283-f340-4fee-a382-158159722f69
		summarizeBy: none
		sourceColumn: occupation_code

		annotation SummarizationSetBy = Automatic

	column skill_label
		dataType: string
		lineageTag: 83fc851f-84b5-4995-a246-c661cebfaaa5
		summarizeBy: none
		sourceColumn: skill_label

		annotation SummarizationSetBy = Automatic

	column is_matched
		dataType: int64
		formatString: 0
		lineageTag: 4c153052-65e0-4906-90c5-ec35f91035da
		summarizeBy: sum
		sourceColumn: is_matched

		annotation SummarizationSetBy = Automatic

	column source_name
		dataType: string
		lineageTag: f0dcf12e-2ad9-4f8e-a8c6-5ae31391ec76
		summarizeBy: none
		sourceColumn: source_name

		annotation SummarizationSetBy = Automatic

	column source_url
		dataType: string
		lineageTag: 51982b74-8769-4a5e-94fe-212277e271d0
		summarizeBy: none
		sourceColumn: source_url

		annotation SummarizationSetBy = Automatic

	column source_page
		dataType: string
		lineageTag: 6b24e733-4454-4ebc-ba43-fbc48b67598b
		summarizeBy: none
		sourceColumn: source_page

		annotation SummarizationSetBy = Automatic

	partition fct_skill_evidence = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\DUMMY_fct_skill_evidence.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"occupation_code", type text}, {"skill_label", type text}, {"is_matched", Int64.Type}, {"source_name", type text}, {"source_url", type text}, {"source_page", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

